// Need to use the React-specific entry point to import createApi
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

// Define a service using a base URL and expected endpoints
export const dndApi = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: 'https://www.dnd5eapi.co/api/' }),
  tagTypes : [],
  endpoints: (builder) => ({
    //! getData as prop
    getRaceData: builder.query({
      query: (name) => `races/${name}`,
    }),
    getClassData: builder.query({
      query: (name) => `classes/${name}`
    })
  }),
})

// Export hooks for usage in functional components, which are
// auto-generated based on the defined endpoints
//! useGetRaceDataQuery is autogenerated from getRaceData above. "use" + prop(Pascal-cased) + "query"
export const { useGetRaceDataQuery, useGetClassDataQuery } = dndApi;