// Need to use the React-specific entry point to import createApi
import { createApi, fetchBaseQuery } from '@reduxjs/toolkit/query/react'

// Define a service using a base URL and expected endpoints
export const mongoApi = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: 'https://localhost:3000/' }),
  tagTypes : ['Post', 'User', 'Delete'],
  endpoints: (builder) => ({
    //! getData as prop
    getCharacters: builder.query({
      query: (id) => `/api/`,
    })
  }),
})

// Export hooks for usage in functional components, which are
// auto-generated based on the defined endpoints
//! useGetCharactersQuery is autogenerated from getRaceCharacters above. "use" + prop(Pascal-cased) + "query"
export const { useGetCharactersQuery } = mongoApi;