GET http://localhost:3000/api/
###
GET http://localhost:3000/api/63237843d3f965161423e5e2
###
POST http://localhost:3000/api/
Content-Type: application/json

{
    "playerName": "Sam",
    "charName": "Scanlan Shorthalt",
    "race": "gnome",
    "class": {
        "className": "bard",
        "classLevel": 1
    },
    "background": "Performer",
    "alignment": "CG",
    "abilities": {
        "str": 13,
        "dex": 11,
        "con": 16,
        "int": 16,
        "wis": 7,
        "cha": 22
        }
}
###
DELETE http://localhost:3000/api/63237843d3f965161423e5e2
###
PATCH http://localhost:3000/api/63237843d3f965161423e5e2
Content-Type: application/json

{
    "playerName": "Matthew from api patch"
}

