GET http://localhost:3000/api/
###
GET http://localhost:3000/api/63237843d3f965161423e5e2
###
POST http://localhost:3000/api/
Content-Type: application/json

{
    "playerName": "Matthew testing from router",
    "charName": "Thorival",
    "race": "human",
    "class": {
        "className": "wizard",
        "classLevel": 1
    },
    "background": "nobel",
    "alignment": "LG",
    "abilities": {
        "str": 11,
        "dex": 11,
        "con": 11,
        "int": 1,
        "wis": 11,
        "cha": 11
        }
}
###
DELETE http://localhost:3000/api/6323744a59b82dacadde6e71
###
PATCH http://localhost:3000/api/63237843d3f965161423e5e2
Content-Type: application/json

{
    "playerName": "Matthew from api patch"
}

